openapi: 3.0.3
info:
  title: Sample
  description: Your amazing API !
  version: v1
  contact:
    name: John Doe
    email: john.doe@example.com
  license:
    name: MIT
paths:
  /tests:
    verbs:
      - GET
      - POST
  /tests/{test_ref}:
    verbs:
      - GET
      - PUT
      - PATH
      - DELETE
